### ISSUE TITLE
ltafdb web page is moved to archived, so dl_database can't find the URL

### ISSUE THREAD

**Issue by khtad** [MIT-LCP/physionet#125]
This code:

import wfdb
import os

def main():
    db = 'ltafdb'
    wfdb.dl_database(db_dir=db,
                     dl_dir=os.getcwd())

if __name__ == '__main__':
    main()

returns the following error:

Traceback (most recent call last):
  File "C:/wfdbAFIB/downloadDB.py", line 12, in <module>
    main()
  File "C:/wfdbAFIB/downloadDB.py", line 8, in main
    dl_dir=os.getcwd())
  File "C:\Users\micha\Anaconda3\lib\site-packages\wfdb\io\record.py", line 2253, in dl_database
    r.raise_for_status()
  File "C:\Users\micha\Anaconda3\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://physionet.org/content/ltafdb/1.0.0%5C/

The URL that the subroutine is pointing at is indeed 404 because the DB has been moved to https://archive.physionet.org/physiobank/database/ltafdb/.

**Comment by tompollard** [comment]
Please could you raise this issue on the WFDB package repo? https://github.com/MIT-LCP/wfdb-python

**Comment by tompollard** [comment]
Reposted at: https://github.com/MIT-LCP/wfdb-python/issues/252 (thanks!)
